# Generated by Django 5.1.3 on 2025-08-06 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('studentclass', models.CharField(choices=[('1', 'Class 1'), ('8', 'Class 8'), ('7', 'Class 7'), ('4', 'Class 4'), ('2', 'Class 2'), ('10', 'Class 10'), ('6', 'Class 6'), ('12', 'Class 12'), ('11', 'Class 11'), ('', 'SELECT'), ('5', 'Class 5'), ('9', 'Class 9'), ('3', 'Class 3')], default='SELECT', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
