# Generated by Django 5.1.3 on 2025-08-06 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentinfomodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('9', 'Class 9'), ('7', 'Class 7'), ('2', 'Class 2'), ('3', 'Class 3'), ('6', 'Class 6'), ('4', 'Class 4'), ('10', 'Class 10'), ('1', 'Class 1'), ('5', 'Class 5'), ('8', 'Class 8'), ('11', 'Class 11'), ('', 'SELECT'), ('12', 'Class 12')], default='SELECT', max_length=10),
        ),
        migrations.CreateModel(
            name='TeacherInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('', 'SELECT')], default='SELECT', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
