# Generated by Django 5.1.3 on 2025-08-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentinfomodel_studentclass_teacherinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('9', 'Class 9'), ('11', 'Class 11'), ('8', 'Class 8'), ('5', 'Class 5'), ('', 'SELECT'), ('1', 'Class 1'), ('4', 'Class 4'), ('12', 'Class 12'), ('10', 'Class 10'), ('2', 'Class 2'), ('3', 'Class 3'), ('6', 'Class 6'), ('7', 'Class 7')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('', 'SELECT'), ('English', 'English')], default='SELECT', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Biology', 'Biology'), ('', 'SELECT'), ('Arts', 'Arts'), ('Physics', 'Physics'), ('Sanskrit', 'Sanskrit'), ('Social Science', 'Social Science'), ('Hindi', 'Hindi'), ('Maths', 'Maths'), ('Computer', 'Computer'), ('Chemistry', 'Chemistry'), ('English', 'English')], default='SELECT', max_length=100),
        ),
    ]
