# Generated by Django 5.1.3 on 2025-08-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentinfomodel_studentclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('4', 'Class 4'), ('1', 'Class 1'), ('', 'SELECT'), ('3', 'Class 3'), ('2', 'Class 2'), ('12', 'Class 12'), ('6', 'Class 6'), ('11', 'Class 11'), ('10', 'Class 10'), ('5', 'Class 5'), ('9', 'Class 9'), ('7', 'Class 7'), ('8', 'Class 8')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='language',
            field=models.CharField(choices=[('', 'SELECT'), ('Hindi', 'Hindi'), ('English', 'English')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Biology', 'Biology'), ('English', 'English'), ('', 'SELECT'), ('Hindi', 'Hindi'), ('Social Science', 'Social Science'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Arts', 'Arts'), ('Computer', 'Computer'), ('Sanskrit', 'Sanskrit')], default='', max_length=100),
        ),
    ]
