# Generated by Django 5.1.3 on 2025-08-06 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentinfomodel_studentclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('10', 'Class 10'), ('3', 'Class 3'), ('1', 'Class 1'), ('4', 'Class 4'), ('12', 'Class 12'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('', 'SELECT'), ('11', 'Class 11'), ('5', 'Class 5'), ('9', 'Class 9'), ('2', 'Class 2')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Computer', 'Computer'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Social Science', 'Social Science'), ('', 'SELECT'), ('Arts', 'Arts'), ('Physics', 'Physics')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ClassRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherinfomodel')),
            ],
        ),
    ]
