# Generated by Django 5.1.3 on 2025-08-06 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studentinfomodel_studentclass_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('10', 'Class 10'), ('1', 'Class 1'), ('', 'SELECT'), ('12', 'Class 12'), ('8', 'Class 8'), ('6', 'Class 6'), ('5', 'Class 5'), ('7', 'Class 7'), ('11', 'Class 11'), ('3', 'Class 3'), ('4', 'Class 4'), ('2', 'Class 2'), ('9', 'Class 9')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('', 'SELECT')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Hindi', 'Hindi'), ('', 'SELECT'), ('Physics', 'Physics'), ('English', 'English'), ('Computer', 'Computer'), ('Sanskrit', 'Sanskrit'), ('Biology', 'Biology'), ('Social Science', 'Social Science'), ('Maths', 'Maths'), ('Arts', 'Arts')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentMarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.IntegerField()),
                ('subject2', models.IntegerField()),
                ('subject3', models.IntegerField()),
                ('subject4', models.IntegerField()),
                ('subject5', models.IntegerField()),
                ('subject6', models.IntegerField()),
                ('subject7', models.IntegerField()),
                ('subject8', models.IntegerField()),
                ('subject9', models.IntegerField()),
                ('subject10', models.IntegerField()),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=50)),
                ('student', models.ForeignKey(limit_choices_to={'profile_role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
