# Generated by Django 5.1.3 on 2025-08-06 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_studentinfomodel_studentclass_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('9', 'Class 9'), ('3', 'Class 3'), ('11', 'Class 11'), ('8', 'Class 8'), ('6', 'Class 6'), ('12', 'Class 12'), ('10', 'Class 10'), ('', 'SELECT'), ('1', 'Class 1'), ('2', 'Class 2'), ('4', 'Class 4'), ('5', 'Class 5'), ('7', 'Class 7')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentmarksmodel',
            name='student',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('', 'SELECT')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('Chemistry', 'Chemistry'), ('Arts', 'Arts'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('English', 'English'), ('', 'SELECT'), ('Sanskrit', 'Sanskrit'), ('Social Science', 'Social Science'), ('Computer', 'Computer')], default='', max_length=100),
        ),
    ]
