# Generated by Django 5.1.3 on 2025-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_studentinfomodel_studentclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('8', 'Class 8'), ('4', 'Class 4'), ('1', 'Class 1'), ('11', 'Class 11'), ('', 'SELECT'), ('5', 'Class 5'), ('7', 'Class 7'), ('12', 'Class 12'), ('9', 'Class 9'), ('3', 'Class 3'), ('10', 'Class 10'), ('2', 'Class 2'), ('6', 'Class 6')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('', 'SELECT'), ('English', 'English')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Sanskrit', 'Sanskrit'), ('Social Science', 'Social Science'), ('Hindi', 'Hindi'), ('Physics', 'Physics'), ('', 'SELECT'), ('Arts', 'Arts'), ('Biology', 'Biology'), ('English', 'English'), ('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Computer', 'Computer')], default='', max_length=100),
        ),
    ]
