# Generated by Django 5.1.3 on 2025-08-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_studentinfomodel_studentclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('8', 'Class 8'), ('3', 'Class 3'), ('6', 'Class 6'), ('5', 'Class 5'), ('4', 'Class 4'), ('', 'SELECT'), ('11', 'Class 11'), ('2', 'Class 2'), ('12', 'Class 12'), ('7', 'Class 7'), ('9', 'Class 9'), ('10', 'Class 10'), ('1', 'Class 1')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Hindi', 'Hindi'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths'), ('Sanskrit', 'Sanskrit'), ('', 'SELECT'), ('Computer', 'Computer'), ('Biology', 'Biology'), ('English', 'English'), ('Physics', 'Physics'), ('Social Science', 'Social Science')], default='', max_length=100),
        ),
    ]
