# Generated by Django 5.1.3 on 2025-08-06 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_studentinfomodel_studentclass_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('4', 'Class 4'), ('3', 'Class 3'), ('10', 'Class 10'), ('12', 'Class 12'), ('2', 'Class 2'), ('6', 'Class 6'), ('7', 'Class 7'), ('9', 'Class 9'), ('', 'SELECT'), ('1', 'Class 1'), ('8', 'Class 8'), ('11', 'Class 11'), ('5', 'Class 5')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='language',
            field=models.CharField(choices=[('', 'SELECT'), ('Hindi', 'Hindi'), ('English', 'English')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Biology', 'Biology'), ('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('', 'SELECT'), ('Arts', 'Arts'), ('Social Science', 'Social Science'), ('Sanskrit', 'Sanskrit'), ('Hindi', 'Hindi'), ('Physics', 'Physics'), ('Computer', 'Computer'), ('English', 'English')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentNoticeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('upload', models.FileField(blank=True, null=True, upload_to='student_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'profile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='notices_received', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'profile__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='notices_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
