# Generated by Django 5.1.3 on 2025-08-06 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_studentinfomodel_studentclass_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('3', 'Class 3'), ('5', 'Class 5'), ('9', 'Class 9'), ('7', 'Class 7'), ('10', 'Class 10'), ('', 'SELECT'), ('12', 'Class 12'), ('1', 'Class 1'), ('2', 'Class 2'), ('4', 'Class 4'), ('8', 'Class 8'), ('11', 'Class 11'), ('6', 'Class 6')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Sanskrit', 'Sanskrit'), ('', 'SELECT'), ('Hindi', 'Hindi'), ('English', 'English'), ('Biology', 'Biology'), ('Arts', 'Arts'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths'), ('Social Science', 'Social Science'), ('Computer', 'Computer')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='GeneralNoticeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('upload', models.FileField(blank=True, null=True, upload_to='general_notices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(limit_choices_to={'profile__role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
