# Generated by Django 5.1.3 on 2025-08-06 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_studentinfomodel_studentclass_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('8', 'Class 8'), ('6', 'Class 6'), ('10', 'Class 10'), ('3', 'Class 3'), ('11', 'Class 11'), ('4', 'Class 4'), ('9', 'Class 9'), ('', 'SELECT'), ('12', 'Class 12'), ('5', 'Class 5'), ('1', 'Class 1'), ('7', 'Class 7'), ('2', 'Class 2')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='language',
            field=models.CharField(choices=[('', 'SELECT'), ('English', 'English'), ('Hindi', 'Hindi')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('English', 'English'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('Hindi', 'Hindi'), ('Social Science', 'Social Science'), ('', 'SELECT'), ('Computer', 'Computer'), ('Sanskrit', 'Sanskrit'), ('Arts', 'Arts')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('student', models.ForeignKey(limit_choices_to={'profile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_receive', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'profile__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
