# Generated by Django 5.1.3 on 2025-08-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_studentinfomodel_studentclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarksmodel',
            name='subject10',
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('2', 'Class 2'), ('9', 'Class 9'), ('6', 'Class 6'), ('', 'SELECT'), ('4', 'Class 4'), ('3', 'Class 3'), ('10', 'Class 10'), ('11', 'Class 11'), ('7', 'Class 7'), ('1', 'Class 1'), ('12', 'Class 12'), ('8', 'Class 8'), ('5', 'Class 5')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentmarksmodel',
            name='subject7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarksmodel',
            name='subject8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarksmodel',
            name='subject9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Maths', 'Maths'), ('', 'SELECT'), ('Physics', 'Physics'), ('English', 'English'), ('Sanskrit', 'Sanskrit'), ('Chemistry', 'Chemistry'), ('Hindi', 'Hindi'), ('Social Science', 'Social Science'), ('Computer', 'Computer'), ('Biology', 'Biology')], default='', max_length=100),
        ),
    ]
