# Generated by Django 5.1.3 on 2025-08-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_studentmarksmodel_subject10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('9', 'Class 9'), ('10', 'Class 10'), ('3', 'Class 3'), ('1', 'Class 1'), ('8', 'Class 8'), ('5', 'Class 5'), ('7', 'Class 7'), ('12', 'Class 12'), ('6', 'Class 6'), ('', 'SELECT'), ('11', 'Class 11'), ('4', 'Class 4'), ('2', 'Class 2')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('', 'SELECT')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Sanskrit', 'Sanskrit'), ('Physics', 'Physics'), ('Computer', 'Computer'), ('Chemistry', 'Chemistry'), ('Arts', 'Arts'), ('Hindi', 'Hindi'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('Social Science', 'Social Science'), ('', 'SELECT'), ('English', 'English')], default='', max_length=100),
        ),
    ]
