# Generated by Django 5.1.3 on 2025-08-07 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_studentinfomodel_studentclass_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('8', 'Class 8'), ('1', 'Class 1'), ('2', 'Class 2'), ('5', 'Class 5'), ('6', 'Class 6'), ('', 'SELECT'), ('9', 'Class 9'), ('4', 'Class 4'), ('10', 'Class 10'), ('3', 'Class 3'), ('11', 'Class 11'), ('12', 'Class 12'), ('7', 'Class 7')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('', 'SELECT'), ('Hindi', 'Hindi')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Social Science', 'Social Science'), ('Arts', 'Arts'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('', 'SELECT'), ('Computer', 'Computer'), ('Maths', 'Maths'), ('Physics', 'Physics')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='AssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'profile__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
