# Generated by Django 5.1.3 on 2025-08-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_studentinfomodel_studentclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmodel',
            name='class_name',
            field=models.CharField(choices=[('', 'SELECT'), ('2', 'Class 2'), ('8', 'Class 8'), ('5', 'Class 5'), ('9', 'Class 9'), ('7', 'Class 7'), ('12', 'Class 12'), ('3', 'Class 3'), ('6', 'Class 6'), ('1', 'Class 1'), ('11', 'Class 11'), ('10', 'Class 10'), ('4', 'Class 4')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('', 'SELECT'), ('2', 'Class 2'), ('8', 'Class 8'), ('5', 'Class 5'), ('9', 'Class 9'), ('7', 'Class 7'), ('12', 'Class 12'), ('3', 'Class 3'), ('6', 'Class 6'), ('1', 'Class 1'), ('11', 'Class 11'), ('10', 'Class 10'), ('4', 'Class 4')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='language',
            field=models.CharField(choices=[('', 'SELECT'), ('English', 'English'), ('Hindi', 'Hindi')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('', 'SELECT'), ('Biology', 'Biology'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Social Science', 'Social Science'), ('Physics', 'Physics'), ('English', 'English'), ('Computer', 'Computer'), ('Maths', 'Maths'), ('Arts', 'Arts'), ('Chemistry', 'Chemistry')], default='', max_length=100),
        ),
    ]
