# Generated by Django 5.1.3 on 2025-08-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_assignmentmodel_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='studentclass',
            field=models.CharField(choices=[('8', 'Class 8'), ('9', 'Class 9'), ('4', 'Class 4'), ('12', 'Class 12'), ('1', 'Class 1'), ('7', 'Class 7'), ('', 'SELECT'), ('3', 'Class 3'), ('6', 'Class 6'), ('10', 'Class 10'), ('11', 'Class 11'), ('5', 'Class 5'), ('2', 'Class 2')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('', 'SELECT')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfomodel',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Social Science', 'Social Science'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('', 'SELECT'), ('Physics', 'Physics'), ('Hindi', 'Hindi'), ('Arts', 'Arts'), ('Computer', 'Computer'), ('English', 'English'), ('Sanskrit', 'Sanskrit')], default='', max_length=100),
        ),
    ]
